import type { Metadata } from "next";
import { Inter, Comfortaa, Nunito, Raleway } from "next/font/google";
import "./globals.css";
import Navbars from "./components/Navbar";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });
const comfortaa = Comfortaa({ subsets: ["latin"] });
const nunito = Nunito({subsets:["latin"]})
const raleway = Raleway({subsets:["latin"]})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${comfortaa.className} ${nunito.className} ${raleway.className}`} >
        <Navbars/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
